spring:
  output:
    ansi:
      enabled: always

format:
  date-time: "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"

service:
  crawl-news:
    enable: false
    cron-job: 0 0 */3 * * *

  crawl-politics-rulers:
    enable: false
    testing: false
    cron-job: 0 0 0 * * *

  crawl-world-cup-stats:
    enable: true
    testing: false
    cron-job: 0 0 */1 * * *

logging:
  level:
    org:
      springframework: INFO
    app:
      netlify:
        nmhillusion: DEBUG