spring:
  output:
    ansi:
      enabled: always
  jackson:
    time-zone: GMT+07:00

time-zone: GMT+07:00

format:
  date-time: "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"

service:
  crawl-news:
    enable: true
    testing: false
    cron-job: 0 0 6,11,16,20 * * *

  crawl-image:
    enable: true
    testing: false
    cron-job: 0 0 5 * * *

  politics:
    crawl-politics-rulers:
      enable: false
      testing: false
      cron-job: 0 0 0 * * *

    crawl-wanted-people:
      enable: false
      testing: false
      cron-job: 0 0 0 * * *

  crawl-world-cup-stats:
    enable: false
    testing: false
    cron-job: 0 0/15 * * * *

  crawl-euro-cup-stats:
    enable: true
    testing: false
    cron-job: 0 0/15 * * * *

logging:
  pattern:
    dateformat: yyyy-MM-dd'T'HH:mm:ssXXX
  level:
    org:
      springframework: INFO
    app:
      netlify:
        nmhillusion: DEBUG