spring:
  output:
    ansi:
      enabled: always

format:
  date-time: "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"

cron-job:
  crawl-news: 0 0 */3 * * *
  crawl-politics-rulers: 0 0 0 * * *

logging:
  level:
    org:
      springframework: INFO
    app:
      netlify:
        nmhillusion: DEBUG